[package]
name = "java-oo-bindgen"
version = "0.1.4"
authors = ["Émile Grégoire <emile@stepfunc.io>"]
edition = "2021"

[dependencies]
oo-bindgen = { path = "../../oo-bindgen" }
dunce = "1.0"
pathdiff = "0.2"
