[package]
name = "java-oo-bindgen"
version = "0.1.0"
authors = ["Émile Grégoire <emile@automatak.com>"]
edition = "2018"

[dependencies]
oo-bindgen = { path = "../../oo-bindgen" }
dunce = "1.0"
heck = "0.3"
