[package]
name = "ci-script"
version = "0.1.0"
authors = ["Ã‰mile GrÃ©goire <emile@automatak.com>"]
edition = "2018"

[dependencies]
oo-bindgen = { path = "../oo-bindgen" }
c-oo-bindgen = { path = "../generators/c-oo-bindgen" }
#dotnet-oo-bindgen = { path = "../generators/dotnet-oo-bindgen" }
#java-oo-bindgen = { path = "../generators/java-oo-bindgen" }
clap = "2.33"
